### ISSUE TITLE
Can we have a control test result and put it onto the read.me

### ISSUE THREAD

**Issue by dng8888** [mingchuno/ABCDEFGHPPP#35]
I am not sure I am right (wrong before) but mine is as below (using minizinc, sort by a b c d e f g h and well p; and btw the pull request is submitted).  For the moderator (mingchuno) to consider to use a test-driven development approach.  

If 0 is allowed i.e. 0...9 can be used:

Compiling primary1q.mzn
Running primary1q.mzn
## 95 - 27 = 68 + 43= 111  
# 

Finished in 34msec

If no 0 is allowed i.e. if only 1...9 can be used:

**Comment by gaplo917** [comment]
Occurrence of leading zero in two digit is not regard as correct solution 

But using 0 should have two more solution

https://github.com/mingchuno/ABCDEFGHPPP/blob/master/swift-functional/output.txt

**Comment by dng8888** [comment]
Amended with the additional constraint i.e. a, c, e, f cannot be 0.

Still I think that is not the in the original intent.  The primary 1 exercise would be more interesting to be done in paper and move around using paper number tile (0 ... 9) around the equation.  With that 3 solutions are all possible (as the original questions have not even mentioned 0) i.e.

(a) Your solution i.e. no 0 digit in the first position, as seems all solutions are like that (at least the python one I checked.)
(b) The solution allows 0 in any position
(c) The solution does not allow 0 in any position.

I put other codes in sub-directory to avoid confusing anyone.  But the result have your expected solution first as well  i.e.

abcedefghppp.mzn same as abcdefghppp-no-1st-pos-0.mzn
    to conform with other solutions.

Compiling abcdefghppp-no-1st-pos-0.mzn
Running abcdefghppp-no-1st-pos-0.mzn

## 85 - 46 = 39 + 72= 111

## 86 - 54 = 32 + 79= 111

## 90 - 27 = 63 + 48= 111

## 90 - 63 = 27 + 84= 111

## 95 - 27 = 68 + 43= 111

# 

Finished in 32msec

(But I did include the result of other version followed this.  It should confuse anyone.)

**Comment by gaplo917** [comment]
Merged , issue close
