### ISSUE TITLE
Other solutions

### ISSUE THREAD

**Issue by mukeshtiwari** [mingchuno/ABCDEFGHPPP#51]
I am using constraint programming and found couple of more solutions. 
99 - 77 = 22, 22 + 89 = 111
65 - 44 = 21, 21 + 90 = 111
81 - 19 = 62, 62 + 49 = 111
22 - 10 = 12, 12 + 99 = 111
Are these correct solution or not according to problems specification ? According to me,  
A != 0 C != 0 E != 0 G != 0 
AB - CD = EF, EF + GH = PPP 
They are valid solutions.
or A B C D E F G H P takes unique value at a time ?

**Comment by jackhftang** [comment]
a,b,c,d,e,f,g,h,p are distinct.

**Comment by mukeshtiwari** [comment]
@jackhftang Thank you

**Comment by gaplo917** [comment]
@mukeshtiwari Thanks for pointing out 

I will update the README for a,b,c,d,e,f,g,h,p are distinct.

Some of the ppl now trying to writing base 17/21 solution to test their algo efficiency 

ie, for base 17
abcd - efgh = ijkl , ijkl + mnop = qqqqq

see if you insterest in writing in hy/ocaml version
